sudo: false
language: go

go:
    - 1.5
    - 1.6
    - 1.7

env:
    global:
        - GO15VENDOREXPERIMENT=1
        - TEST_TIMEOUT_SCALE=10

cache:
  directories:
    - vendor

install:
    - make install_ci

script:
    - make test_ci
    - travis_retry goveralls -coverprofile=cover.out -service=travis-ci
