sudo: false
language: go

go:
    - 1.7
    - 1.8

env:
    global:
        - GO15VENDOREXPERIMENT=1
        - TEST_TIMEOUT_SCALE=10
        - GITHUB_USER=prashantv
        # TODO: Add secret variable to release

cache:
  directories:
    - vendor

install:
    - make install_ci

script:
    - make test_ci
    - travis_retry goveralls -coverprofile=cover.out -service=travis-ci

deploy:
    - provider: script
      script: scripts/release.sh $TRAVIS_TAG
      skip_cleanup: true
      on:
          tags: true
